/**
 * YouTube字幕翻译助手 - 核心数据类型定义
 * @fileoverview 定义扩展中使用的所有核心数据结构
 * @version 5.24.6
 * @author AI Assistant
 */

// ================================
// 🎯 基础类型定义
// ================================

/**
 * 语言代码类型 (遵循 BCP-47 标准)
 */
export type LanguageCode = string;

/**
 * 视频ID类型
 */
export type VideoId = string;

/**
 * 时间戳类型 (毫秒)
 */
export type Timestamp = number;

/**
 * Hash值类型 (用于缓存验证)
 */
export type HashValue = string;

// ================================
// 🎬 YouTube相关类型
// ================================

/**
 * YouTube字幕轨道信息
 */
export interface SubtitleTrack {
  /** 轨道ID */
  id: string;
  /** 语言代码 */
  languageCode: LanguageCode;
  /** 显示名称 */
  displayName: string;
  /** 是否为自动生成字幕 */
  isAutoGenerated: boolean;
  /** 是否为默认轨道 */
  isDefault: boolean;
}

/**
 * 字幕事件 (原始YouTube字幕数据)
 */
export interface SubtitleEvent {
  /** 开始时间 (秒) */
  start: number;
  /** 持续时间 (秒) */
  duration: number;
  /** 字幕文本 */
  text: string;
  /** 事件ID (可选) */
  id?: string;
}

/**
 * 处理后的字幕事件 (扩展内部使用)
 * ✨ 统一后的权威定义
 */
export interface ProcessedSubtitleEvent {
  /** 事件唯一标识 (通常是原始字幕事件的ID或行号) */
  id: string;
  /** 开始时间 (秒) */
  start: number;
  /** 结束时间 (秒) */
  end: number;
  /** 原始文本 */
  originalText: string;
  /** 翻译文本 */
  translatedText: string | null;
  /** 源语言代码 */
  sourceLangCode: LanguageCode;
  /** 目标语言代码 */
  targetLangCode: LanguageCode;
  /** 原始文本Hash (用于缓存匹配) */
  textHash: HashValue;
}

// ================================
// 📊 翻译相关类型
// ================================

/**
 * 翻译服务提供商
 */
export enum TranslationProvider {
  OPENAI = 'openai',
  GOOGLE = 'google',
  MICROSOFT = 'microsoft',
  BAIDU = 'baidu'
}

/**
 * 翻译请求
 */
export interface TranslationRequest {
  /** 要翻译的文本 */
  text: string;
  /** 源语言 */
  sourceLanguage: LanguageCode;
  /** 目标语言 */
  targetLanguage: LanguageCode;
  /** 翻译服务提供商 */
  provider: TranslationProvider;
  /** 请求ID (用于追踪) */
  requestId: string;
  /** 文本Hash */
  textHash: HashValue;
}

/**
 * 翻译响应
 */
export interface TranslationResponse {
  /** 翻译后的文本 */
  translatedText: string;
  /** 源语言 (检测到的) */
  detectedSourceLanguage?: LanguageCode;
  /** 置信度 (0-1) */
  confidence?: number;
  /** 请求ID */
  requestId: string;
  /** 翻译服务提供商 */
  provider: TranslationProvider;
  /** 响应时间戳 */
  timestamp: Timestamp;
}

/**
 * 翻译错误信息
 */
export interface TranslationError {
  /** 错误代码 */
  code: string;
  /** 错误消息 */
  message: string;
  /** 请求ID */
  requestId: string;
  /** 错误时间戳 */
  timestamp: Timestamp;
  /** 是否可重试 */
  retryable: boolean;
}

// ================================
// 🎮 UI状态类型
// ================================

/**
 * 翻译按钮状态
 */
export enum TranslationButtonState {
  /** 关闭状态 */
  OFF = 'off',
  /** 开启状态 */
  ON = 'on',
  /** 加载中 */
  LOADING = 'loading',
  /** 错误状态 */
  ERROR = 'error'
}

/**
 * 设置按钮状态
 */
export enum SettingsButtonState {
  /** 正常状态 */
  NORMAL = 'normal',
  /** 激活状态 */
  ACTIVE = 'active',
  /** 有冲突警告 */
  WARNING = 'warning'
}

/**
 * UI控制器状态
 */
export interface UIControllerState {
  /** 翻译按钮状态 */
  translationButton: TranslationButtonState;
  /** 设置按钮状态 */
  settingsButton: SettingsButtonState;
  /** 是否显示字幕 */
  showSubtitles: boolean;
  /** 当前视频ID */
  currentVideoId?: VideoId;
  /** 最后更新时间 */
  lastUpdate: Timestamp;
}

// ================================
// 🌐 语言处理类型
// ================================

/**
 * 语言检测结果
 */
export interface LanguageDetectionResult {
  /** 检测到的语言代码 */
  languageCode: LanguageCode;
  /** 置信度 (0-1) */
  confidence: number;
  /** 检测方法 */
  method: 'youtube' | 'content' | 'browser' | 'default';
}

/**
 * 语言冲突信息
 */
export interface LanguageConflict {
  /** 源语言 (YouTube) */
  sourceLanguage: LanguageCode;
  /** 目标语言 (用户设置) */
  targetLanguage: LanguageCode;
  /** 冲突类型 */
  conflictType: 'same_language' | 'unsupported_source' | 'unsupported_target';
  /** 建议的解决方案 */
  suggestion?: string;
}

// ================================
// 🔄 缓存相关类型
// ================================

/**
 * 缓存条目基础接口
 */
export interface CacheEntry<T = any> {
  /** 缓存数据 */
  data: T;
  /** 创建时间 */
  createdAt: Timestamp;
  /** 过期时间 */
  expiresAt: Timestamp;
  /** 访问次数 */
  accessCount: number;
  /** 最后访问时间 */
  lastAccessedAt: Timestamp;
  /** 数据Hash */
  hash: HashValue;
}

/**
 * 字幕缓存条目
 */
export interface SubtitleCacheEntry extends CacheEntry<SubtitleEvent[]> {
  /** 视频ID */
  videoId: VideoId;
  /** 语言代码 */
  languageCode: LanguageCode;
  /** 字幕轨道ID */
  trackId: string;
}

/**
 * 翻译缓存条目
 */
export interface TranslationCacheEntry extends CacheEntry<string> {
  /** 原文Hash */
  textHash: HashValue;
  /** 源语言 */
  sourceLanguage: LanguageCode;
  /** 目标语言 */
  targetLanguage: LanguageCode;
  /** 翻译服务提供商 */
  provider: TranslationProvider;
}

// ================================
// 📋 业务逻辑类型
// ================================

/**
 * 视频上下文信息
 */
export interface VideoContext {
  /** 视频ID */
  videoId: VideoId;
  /** 视频标题 */
  title?: string;
  /** 视频URL */
  url: string;
  /** 可用字幕轨道 */
  availableSubtitles: SubtitleTrack[];
  /** 当前字幕轨道 */
  currentSubtitleTrack?: SubtitleTrack;
  /** 检测到的源语言 */
  detectedSourceLanguage?: LanguageCode;
  /** 页面加载时间 */
  pageLoadTime: Timestamp;
}

/**
 * 翻译会话信息
 */
export interface TranslationSession {
  /** 会话ID */
  sessionId: string;
  /** 视频上下文 */
  videoContext: VideoContext;
  /** 源语言 */
  sourceLanguage: LanguageCode;
  /** 目标语言 */
  targetLanguage: LanguageCode;
  /** 翻译服务提供商 */
  provider: TranslationProvider;
  /** 会话开始时间 */
  startTime: Timestamp;
  /** 翻译的字幕数量 */
  translatedCount: number;
  /** 缓存命中次数 */
  cacheHits: number;
  /** 是否活跃 */
  isActive: boolean;
}

// ================================
// 🎯 导出类型集合
// ================================

/**
 * 所有语言相关类型
 */
export type LanguageTypes = {
  LanguageCode: LanguageCode;
  LanguageDetectionResult: LanguageDetectionResult;
  LanguageConflict: LanguageConflict;
};

/**
 * 所有字幕相关类型
 */
export type SubtitleTypes = {
  SubtitleTrack: SubtitleTrack;
  SubtitleEvent: SubtitleEvent;
  ProcessedSubtitleEvent: ProcessedSubtitleEvent;
  SubtitleCacheEntry: SubtitleCacheEntry;
};

/**
 * 所有翻译相关类型
 */
export type TranslationTypes = {
  TranslationProvider: TranslationProvider;
  TranslationRequest: TranslationRequest;
  TranslationResponse: TranslationResponse;
  TranslationError: TranslationError;
  TranslationCacheEntry: TranslationCacheEntry;
  TranslationSession: TranslationSession;
};

/**
 * 所有UI相关类型
 */
export type UITypes = {
  TranslationButtonState: TranslationButtonState;
  SettingsButtonState: SettingsButtonState;
  UIControllerState: UIControllerState;
}; 