/**
 * YouTube字幕翻译助手 - 消息通信类型定义
 * @fileoverview 定义扩展组件间消息传递的所有数据结构和协议
 * @version 5.24.6
 * @author AI Assistant
 */

import {
  LanguageCode,
  VideoId,
  Timestamp,
  TranslationProvider,
  SubtitleEvent,
  ProcessedSubtitleEvent,
  TranslationButtonState,
  SettingsButtonState
} from './core-types';

import { UserPreferences } from './user-preferences-types';
import { RuntimeState } from './runtime-state-types';

// ================================
// 🎯 消息基础类型
// ================================

/**
 * UI事件的结构化类型定义
 * 用于MessageBus中传递的UI相关事件
 */
export interface UIActionEvent {
  /**
   * UI事件的具体类型
   */
  type: 'button_click' | 'tooltip_show' | 'state_change';
  
  /**
   * 事件携带的数据
   */
  payload: {
    /**
     * 按钮类型，在 button_click 事件中使用
     */
    buttonType?: 'translate' | 'settings';
    
    /**
     * tooltip文本，在 tooltip_show 事件中使用
     */
    tooltipText?: string;

    /**
     * 新的状态值
     */
    newState?: any;
    
    /**
     * 触发事件的源头
     */
    source?: string;
  };
}

/**
 * 消息类型枚举
 */
export enum MessageType {
  // 系统控制消息
  EXTENSION_INIT = 'extension_init',
  EXTENSION_SHUTDOWN = 'extension_shutdown',
  
  // 字幕相关消息
  SUBTITLE_DETECTED = 'subtitle_detected',
  SUBTITLE_UPDATED = 'subtitle_updated',
  SUBTITLE_REQUEST = 'subtitle_request',
  
  // 翻译相关消息
  TRANSLATION_REQUEST = 'translation_request',
  TRANSLATION_RESPONSE = 'translation_response',
  TRANSLATION_ERROR = 'translation_error',
  TRANSLATION_TOGGLE = 'translation_toggle',
  
  // UI状态消息
  UI_STATE_UPDATE = 'ui_state_update',
  BUTTON_STATE_CHANGE = 'button_state_change',
  
  // 设置相关消息
  SETTINGS_GET = 'settings_get',
  SETTINGS_UPDATE = 'settings_update',
  SETTINGS_RESET = 'settings_reset',
  
  // SidePanel消息
  SIDEPANEL_OPEN = 'sidepanel_open',
  SIDEPANEL_CLOSE = 'sidepanel_close',
  SIDEPANEL_DATA_REQUEST = 'sidepanel_data_request',
  SIDEPANEL_DATA_RESPONSE = 'sidepanel_data_response',
  
  // 缓存管理消息
  CACHE_GET = 'cache_get',
  CACHE_SET = 'cache_set',
  CACHE_CLEAR = 'cache_clear',
  
  // 错误处理消息
  ERROR_REPORT = 'error_report',
  SHOW_ERROR_MESSAGE = 'show_error_message',
  CLEAR_ERROR_MESSAGE = 'clear_error_message',
  
  // 性能监控消息
  PERFORMANCE_STATS = 'performance_stats'
}

/**
 * 消息发送者类型
 */
export enum MessageSender {
  CONTENT_SCRIPT = 'content_script',
  MAIN_WORLD_SCRIPT = 'main_world_script',
  BACKGROUND_SCRIPT = 'background_script',
  SIDEPANEL = 'sidepanel',
  POPUP = 'popup'
}

/**
 * 消息优先级
 */
export enum MessagePriority {
  LOW = 'low',
  NORMAL = 'normal',
  HIGH = 'high',
  URGENT = 'urgent'
}

/**
 * 基础消息接口
 */
export interface BaseMessage {
  /** 消息类型 */
  type: MessageType;
  /** 消息ID (用于追踪和响应) */
  messageId: string;
  /** 发送者 */
  sender: MessageSender;
  /** 接收者 (可选，用于定向发送) */
  receiver?: MessageSender;
  /** 时间戳 */
  timestamp: Timestamp;
  /** 消息优先级 */
  priority: MessagePriority;
  /** 标签页ID (可选) */
  tabId?: number;
  /** 响应超时时间 (毫秒) */
  timeout?: number;
}

/**
 * 响应消息接口
 */
export interface ResponseMessage<T = any> extends BaseMessage {
  /** 原始消息ID */
  originalMessageId: string;
  /** 是否成功 */
  success: boolean;
  /** 响应数据 */
  data?: T;
  /** 错误信息 */
  error?: string;
}

// ================================
// 🎬 字幕相关消息
// ================================

/**
 * 字幕检测消息
 */
export interface SubtitleDetectedMessage extends BaseMessage {
  type: MessageType.SUBTITLE_DETECTED;
  data: {
    videoId: VideoId;
    languageCode: LanguageCode;
    trackId: string;
    isAutoGenerated: boolean;
    availableTracks: Array<{
      id: string;
      languageCode: LanguageCode;
      displayName: string;
      isAutoGenerated: boolean;
    }>;
  };
}

/**
 * 字幕更新消息
 */
export interface SubtitleUpdatedMessage extends BaseMessage {
  type: MessageType.SUBTITLE_UPDATED;
  data: {
    videoId: VideoId;
    events: SubtitleEvent[];
    languageCode: LanguageCode;
    trackId: string;
  };
}

/**
 * 字幕请求消息
 */
export interface SubtitleRequestMessage extends BaseMessage {
  type: MessageType.SUBTITLE_REQUEST;
  data: {
    videoId: VideoId;
    languageCode?: LanguageCode;
    trackId?: string;
    forceRefresh?: boolean;
  };
}

// ================================
// 📊 翻译相关消息
// ================================

/**
 * 翻译请求消息
 */
export interface TranslationRequestMessage extends BaseMessage {
  type: MessageType.TRANSLATION_REQUEST;
  data: {
    text: string;
    sourceLanguage: LanguageCode;
    targetLanguage: LanguageCode;
    provider?: TranslationProvider;
    textHash: string;
    batchId?: string;
    priority?: 'high' | 'normal' | 'low';
  };
}

/**
 * 翻译响应消息
 */
export interface TranslationResponseMessage extends BaseMessage {
  type: MessageType.TRANSLATION_RESPONSE;
  data: {
    originalText: string;
    translatedText: string;
    sourceLanguage: LanguageCode;
    targetLanguage: LanguageCode;
    provider: TranslationProvider;
    textHash: string;
    confidence?: number;
    fromCache: boolean;
    batchId?: string;
  };
}

/**
 * 翻译错误消息
 */
export interface TranslationErrorMessage extends BaseMessage {
  type: MessageType.TRANSLATION_ERROR;
  data: {
    originalText: string;
    textHash: string;
    sourceLanguage: LanguageCode;
    targetLanguage: LanguageCode;
    provider: TranslationProvider;
    errorCode: string;
    errorMessage: string;
    retryable: boolean;
    batchId?: string;
  };
}

/**
 * 翻译开关切换消息
 */
export interface TranslationToggleMessage extends BaseMessage {
  type: MessageType.TRANSLATION_TOGGLE;
  data: {
    enabled: boolean;
    videoId?: VideoId;
    sourceLanguage?: LanguageCode;
    targetLanguage?: LanguageCode;
  };
}

// ================================
// 🎮 UI状态消息
// ================================

/**
 * UI状态更新消息
 */
export interface UIStateUpdateMessage extends BaseMessage {
  type: MessageType.UI_STATE_UPDATE;
  data: {
    translationButton?: TranslationButtonState;
    settingsButton?: SettingsButtonState;
    showSubtitles?: boolean;
    videoId?: VideoId;
    sourceLanguage?: LanguageCode;
    targetLanguage?: LanguageCode;
  };
}

/**
 * 按钮状态变更消息
 */
export interface ButtonStateChangeMessage extends BaseMessage {
  type: MessageType.BUTTON_STATE_CHANGE;
  data: {
    buttonType: 'translation' | 'settings';
    newState: TranslationButtonState | SettingsButtonState;
    previousState?: TranslationButtonState | SettingsButtonState;
    reason?: string;
  };
}

// ================================
// ⚙️ 设置相关消息
// ================================

/**
 * 设置获取消息
 */
export interface SettingsGetMessage extends BaseMessage {
  type: MessageType.SETTINGS_GET;
  data: {
    keys?: string[];
    includeDefaults?: boolean;
  };
}

/**
 * 设置更新消息
 */
export interface SettingsUpdateMessage extends BaseMessage {
  type: MessageType.SETTINGS_UPDATE;
  data: {
    preferences: Partial<UserPreferences>;
    merge?: boolean;
    skipValidation?: boolean;
  };
}

/**
 * 设置重置消息
 */
export interface SettingsResetMessage extends BaseMessage {
  type: MessageType.SETTINGS_RESET;
  data: {
    sections?: string[];
    confirmReset?: boolean;
  };
}

// ================================
// 🎛️ SidePanel消息
// ================================

/**
 * SidePanel打开消息
 */
export interface SidePanelOpenMessage extends BaseMessage {
  type: MessageType.SIDEPANEL_OPEN;
  data: {
    tabId: number;
    initialTab?: 'translation' | 'settings' | 'about';
    videoId?: VideoId;
  };
}

/**
 * SidePanel关闭消息
 */
export interface SidePanelCloseMessage extends BaseMessage {
  type: MessageType.SIDEPANEL_CLOSE;
  data: {
    tabId: number;
    reason?: 'user_action' | 'tab_change' | 'system';
  };
}

/**
 * SidePanel数据请求消息
 */
export interface SidePanelDataRequestMessage extends BaseMessage {
  type: MessageType.SIDEPANEL_DATA_REQUEST;
  data: {
    requestType: 'full_state' | 'preferences' | 'runtime_state' | 'video_info';
    tabId?: number;
    videoId?: VideoId;
  };
}

/**
 * SidePanel数据响应消息
 */
export interface SidePanelDataResponseMessage extends BaseMessage {
  type: MessageType.SIDEPANEL_DATA_RESPONSE;
  data: {
    requestType: string;
    preferences?: UserPreferences;
    runtimeState?: RuntimeState;
    videoInfo?: {
      videoId: VideoId;
      title?: string;
      currentLanguage?: LanguageCode;
      availableLanguages: LanguageCode[];
      translationActive: boolean;
    };
    languageConflict?: {
      detected: boolean;
      sourceLanguage: LanguageCode;
      targetLanguage: LanguageCode;
      conflictType: string;
      suggestion?: string;
    };
  };
}

// ================================
// 💾 缓存管理消息
// ================================

/**
 * 缓存获取消息
 */
export interface CacheGetMessage extends BaseMessage {
  type: MessageType.CACHE_GET;
  data: {
    cacheType: 'translation' | 'subtitle' | 'video_language';
    key: string;
    videoId?: VideoId;
    languagePair?: {
      source: LanguageCode;
      target: LanguageCode;
    };
  };
}

/**
 * 缓存设置消息
 */
export interface CacheSetMessage extends BaseMessage {
  type: MessageType.CACHE_SET;
  data: {
    cacheType: 'translation' | 'subtitle' | 'video_language';
    key: string;
    value: any;
    ttl?: number;
    videoId?: VideoId;
    metadata?: Record<string, any>;
  };
}

/**
 * 缓存清理消息
 */
export interface CacheClearMessage extends BaseMessage {
  type: MessageType.CACHE_CLEAR;
  data: {
    cacheType?: 'translation' | 'subtitle' | 'video_language' | 'all';
    pattern?: string;
    videoId?: VideoId;
    olderThan?: Timestamp;
  };
}

// ================================
// 🚨 错误处理消息
// ================================

/**
 * 错误报告消息
 */
export interface ErrorReportMessage extends BaseMessage {
  type: MessageType.ERROR_REPORT;
  data: {
    errorType: 'translation' | 'subtitle' | 'ui' | 'storage' | 'network' | 'system';
    errorCode: string;
    errorMessage: string;
    stack?: string;
    context?: {
      videoId?: VideoId;
      tabId?: number;
      userAgent?: string;
      url?: string;
      operation?: string;
    };
    metadata?: Record<string, any>;
    severity: 'low' | 'medium' | 'high' | 'critical';
  };
}

/**
 * 显示错误消息（用于在字幕区域显示）
 */
export interface ShowErrorMessage extends BaseMessage {
  type: MessageType.SHOW_ERROR_MESSAGE;
  data: {
    message: string;
    duration?: number; // 消息显示时间（毫秒），默认5000
    level?: 'info' | 'warning' | 'error'; // 错误级别
  };
}

/**
 * 清除错误消息
 */
export interface ClearErrorMessage extends BaseMessage {
  type: MessageType.CLEAR_ERROR_MESSAGE;
  data?: {};
}

// ================================
// 📈 性能监控消息
// ================================

/**
 * 性能统计消息
 */
export interface PerformanceStatsMessage extends BaseMessage {
  type: MessageType.PERFORMANCE_STATS;
  data: {
    statsType: 'translation' | 'cache' | 'memory' | 'network';
    metrics: {
      [key: string]: number;
    };
    timeRange: {
      start: Timestamp;
      end: Timestamp;
    };
    context?: {
      videoId?: VideoId;
      tabId?: number;
      provider?: TranslationProvider;
    };
  };
}

// ================================
// 🎯 消息联合类型
// ================================

/**
 * 所有消息类型的联合
 */
export type ExtensionMessage = 
  | SubtitleDetectedMessage
  | SubtitleUpdatedMessage
  | SubtitleRequestMessage
  | TranslationRequestMessage
  | TranslationResponseMessage
  | TranslationErrorMessage
  | TranslationToggleMessage
  | UIStateUpdateMessage
  | ButtonStateChangeMessage
  | SettingsGetMessage
  | SettingsUpdateMessage
  | SettingsResetMessage
  | SidePanelOpenMessage
  | SidePanelCloseMessage
  | SidePanelDataRequestMessage
  | SidePanelDataResponseMessage
  | CacheGetMessage
  | CacheSetMessage
  | CacheClearMessage
  | ErrorReportMessage
  | ShowErrorMessage
  | ClearErrorMessage
  | PerformanceStatsMessage;

/**
 * 消息处理器类型
 */
export type MessageHandler<T extends ExtensionMessage = ExtensionMessage> = (
  message: T,
  sender: chrome.runtime.MessageSender,
  sendResponse: (response?: any) => void
) => boolean | void | Promise<any>;

/**
 * 消息路由配置
 */
export interface MessageRoute {
  /** 消息类型 */
  type: MessageType;
  /** 处理器 */
  handler: MessageHandler;
  /** 是否需要响应 */
  requiresResponse?: boolean;
  /** 超时时间 (毫秒) */
  timeout?: number;
  /** 是否允许跨标签页 */
  allowCrossTab?: boolean;
}

/**
 * 消息验证规则
 */
export interface MessageValidationRule {
  /** 消息类型 */
  type: MessageType;
  /** 必需字段 */
  requiredFields: string[];
  /** 可选字段 */
  optionalFields?: string[];
  /** 自定义验证函数 */
  customValidator?: (message: ExtensionMessage) => boolean;
}

// ================================
// 🔧 消息工具类型
// ================================

/**
 * 消息发送选项
 */
export interface MessageSendOptions {
  /** 目标标签页ID */
  tabId?: number;
  /** 是否等待响应 */
  waitForResponse?: boolean;
  /** 超时时间 (毫秒) */
  timeout?: number;
  /** 重试次数 */
  retries?: number;
  /** 重试间隔 (毫秒) */
  retryDelay?: number;
}

/**
 * 消息发送结果
 */
export interface MessageSendResult<T = any> {
  /** 是否成功 */
  success: boolean;
  /** 响应数据 */
  response?: T;
  /** 错误信息 */
  error?: string;
  /** 发送时间戳 */
  sentAt: Timestamp;
  /** 响应时间戳 */
  respondedAt?: Timestamp;
  /** 往返时间 (毫秒) */
  roundTripTime?: number;
}

// ================================
// 🎯 翻译开关相关类型
// ================================

/**
 * 翻译开关请求数据
 */
export interface ToggleTranslateRequest {
  videoId: string;
  newState: boolean;
}

/**
 * 翻译开关响应数据
 */
export interface ToggleTranslateResponse {
  success: boolean;
  action: 'cached' | 'translated' | 'needFetch' | 'stopped' | 'error';
  data?: any;
  message?: string;
  error?: string;
  config?: UserPreferences;
}

// ================================
// 🎯 导出类型集合
// ================================

/**
 * 所有消息相关类型
 */
export type MessageTypes = {
  MessageType: MessageType;
  MessageSender: MessageSender;
  MessagePriority: MessagePriority;
  ExtensionMessage: ExtensionMessage;
  MessageHandler: MessageHandler;
  MessageSendOptions: MessageSendOptions;
  MessageSendResult: MessageSendResult;
}; 