/**
 * 字幕类型定义 - 统一字幕轨道相关接口
 * 
 * 📝 设计说明：
 * - CaptionTrack: YouTube API原始格式，包含完整字幕轨道信息
 * - SimplifiedCaptionTrack: 简化格式，用于内存缓存和存储
 * - 提供双向转换函数，确保类型安全和向后兼容
 * 
 * @author Assistant
 * @date 2024-12-26
 */

import { LanguageCode } from './core-types';
import type { CaptionTrack } from './youtube-types';

// === 简化字幕轨道格式（用于缓存和存储）===

/**
 * 简化字幕轨道接口 - 用于内存缓存和本地存储
 * 提取核心信息，减少存储开销
 */
export interface SimplifiedCaptionTrack {
  /** 字幕文件URL */
  baseUrl: string;
  /** 语言代码 */
  languageCode: string;
  /** 显示名称（如：德语, 法语, English）- 从CaptionTrack.name.simpleText提取 */
  name: string;
  /** 轨道类型（可选）*/
  kind?: 'asr' | 'forced' | undefined;
}

// === 处理过的字幕轨道（用于UI显示）===

/**
 * 处理过的字幕轨道接口 - 用于UI组件显示
 * 包含格式化后的信息，便于前端展示
 */
export interface ProcessedCaptionTrack {
  /** 语言代码 */
  languageCode: LanguageCode;
  /** 显示名称 */
  displayName: string;
  /** 原生名称（如果有）*/
  nativeName?: string;
  /** 是否为自动生成字幕 */
  isAutoGenerated: boolean;
  /** 是否可用于翻译 */
  isTranslatable: boolean;
  /** 原始轨道数据引用 */
  originalTrack: SimplifiedCaptionTrack;
}

// === 字幕轨道查询结果 ===

/**
 * 字幕轨道获取结果
 */
export interface CaptionTrackResult {
  /** 操作是否成功 */
  success: boolean;
  /** 轨道数据 */
  tracks: CaptionTrack[] | null;
  /** 数据来源（内存缓存/API调用）*/
  source: 'memory' | 'api' | 'storage';
  /** 错误信息（如果有）*/
  error?: string;
}

// === 转换工具函数 ===

/**
 * 将CaptionTrack转换为SimplifiedCaptionTrack
 * 用于内存缓存存储时的数据简化
 * 
 * @param track 原始字幕轨道
 * @returns 简化字幕轨道
 */
export function simplifyCaption(track: CaptionTrack): SimplifiedCaptionTrack {
  return {
    baseUrl: track.baseUrl,
    languageCode: track.languageCode,
    name: track.name.simpleText,
    kind: track.kind as 'asr' | 'forced' | undefined
  };
}

/**
 * 批量转换CaptionTrack数组为SimplifiedCaptionTrack数组
 * 
 * @param tracks 原始字幕轨道数组
 * @returns 简化字幕轨道数组
 */
export function simplifyCaptions(tracks: CaptionTrack[]): SimplifiedCaptionTrack[] {
  return tracks.map(simplifyCaption);
}

/**
 * 将SimplifiedCaptionTrack转换回CaptionTrack格式
 * 用于向后兼容，从缓存数据重建完整格式
 * 
 * @param track 简化字幕轨道
 * @param options 可选参数
 * @returns 重建的字幕轨道
 */
export function expandCaption(track: SimplifiedCaptionTrack, options?: {
  vssId?: string;
  isTranslatable?: boolean;
}): CaptionTrack {
  return {
    baseUrl: track.baseUrl,
    name: { simpleText: track.name },
    vssId: options?.vssId || '',
    languageCode: track.languageCode,
    isTranslatable: options?.isTranslatable ?? true,
    kind: track.kind
  };
}

/**
 * 批量转换SimplifiedCaptionTrack数组为CaptionTrack数组
 * 
 * @param tracks 简化字幕轨道数组
 * @param options 可选参数
 * @returns 重建的字幕轨道数组
 */
export function expandCaptions(tracks: SimplifiedCaptionTrack[], options?: {
  vssId?: string;
  isTranslatable?: boolean;
}): CaptionTrack[] {
  return tracks.map(track => expandCaption(track, options));
}

/**
 * 根据语言代码查找最佳匹配的字幕轨道
 * 
 * @param tracks 字幕轨道数组
 * @param languageCode 目标语言代码
 * @returns 匹配的轨道或null
 */
export function findBestMatchingTrack(
  tracks: CaptionTrack[] | SimplifiedCaptionTrack[], 
  languageCode: string
): CaptionTrack | SimplifiedCaptionTrack | null {
  if (!tracks || tracks.length === 0) return null;
  
  // 精确匹配
  const exactMatch = tracks.find(track => track.languageCode === languageCode);
  if (exactMatch) return exactMatch;
  
  // 语言前缀匹配（如：zh-CN -> zh）
  const langPrefix = languageCode.split('-')[0];
  const prefixMatch = tracks.find(track => track.languageCode.startsWith(langPrefix));
  if (prefixMatch) return prefixMatch;
  
  return null;
}

/**
 * 检查字幕轨道是否为自动生成
 * 
 * @param track 字幕轨道
 * @returns 是否为自动生成
 */
export function isAutoGeneratedTrack(track: CaptionTrack | SimplifiedCaptionTrack): boolean {
  return track.kind === 'asr' || track.kind === 'auto';
}

/**
 * 获取字幕轨道的显示名称
 * 兼容不同的数据格式
 * 
 * @param track 字幕轨道
 * @returns 显示名称
 */
export function getTrackDisplayName(track: CaptionTrack | SimplifiedCaptionTrack): string {
  if ('name' in track && typeof track.name === 'object') {
    // CaptionTrack格式
    return (track as CaptionTrack).name.simpleText;
  } else if ('name' in track && typeof track.name === 'string') {
    // SimplifiedCaptionTrack格式
    return (track as SimplifiedCaptionTrack).name;
  }
  
  // 回退到语言代码
  return track.languageCode;
}

// === 类型守卫函数 ===

/**
 * 检查对象是否为CaptionTrack类型
 * 
 * @param track 待检查对象
 * @returns 类型守卫结果
 */
export function isCaptionTrack(track: any): track is CaptionTrack {
  return track && 
         typeof track.baseUrl === 'string' &&
         typeof track.name === 'object' &&
         typeof track.name.simpleText === 'string' &&
         typeof track.vssId === 'string' &&
         typeof track.languageCode === 'string' &&
         typeof track.isTranslatable === 'boolean';
}

/**
 * 检查对象是否为SimplifiedCaptionTrack类型
 * 
 * @param track 待检查对象
 * @returns 类型守卫结果
 */
export function isSimplifiedCaptionTrack(track: any): track is SimplifiedCaptionTrack {
  return track && 
         typeof track.baseUrl === 'string' &&
         typeof track.name === 'string' &&
         typeof track.languageCode === 'string';
}

// === 验证函数 ===

/**
 * 验证字幕轨道数据的完整性
 * 
 * @param track 字幕轨道
 * @returns 验证结果
 */
export function validateCaptionTrack(track: CaptionTrack): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  if (!track.baseUrl || typeof track.baseUrl !== 'string') {
    errors.push('baseUrl is required and must be a string');
  }
  
  if (!track.name || typeof track.name !== 'object' || !track.name.simpleText) {
    errors.push('name.simpleText is required');
  }
  
  if (!track.languageCode || typeof track.languageCode !== 'string') {
    errors.push('languageCode is required and must be a string');
  }
  
  if (typeof track.isTranslatable !== 'boolean') {
    errors.push('isTranslatable must be a boolean');
  }
  
  return {
    valid: errors.length === 0,
    errors
  };
}

/**
 * 验证简化字幕轨道数据的完整性
 * 
 * @param track 简化字幕轨道
 * @returns 验证结果
 */
export function validateSimplifiedCaptionTrack(track: SimplifiedCaptionTrack): { valid: boolean; errors: string[] } {
  const errors: string[] = [];
  
  if (!track.baseUrl || typeof track.baseUrl !== 'string') {
    errors.push('baseUrl is required and must be a string');
  }
  
  if (!track.name || typeof track.name !== 'string') {
    errors.push('name is required and must be a string');
  }
  
  if (!track.languageCode || typeof track.languageCode !== 'string') {
    errors.push('languageCode is required and must be a string');
  }
  
  return {
    valid: errors.length === 0,
    errors
  };
}

// === 统计和调试工具 ===

/**
 * 获取字幕轨道统计信息
 * 
 * @param tracks 字幕轨道数组
 * @returns 统计信息
 */
export function getCaptionTrackStats(tracks: (CaptionTrack | SimplifiedCaptionTrack)[]): {
  total: number;
  byLanguage: Record<string, number>;
  autoGenerated: number;
  translatable: number;
} {
  const stats = {
    total: tracks.length,
    byLanguage: {} as Record<string, number>,
    autoGenerated: 0,
    translatable: 0
  };
  
  tracks.forEach(track => {
    // 语言统计
    stats.byLanguage[track.languageCode] = (stats.byLanguage[track.languageCode] || 0) + 1;
    
    // 自动生成统计
    if (isAutoGeneratedTrack(track)) {
      stats.autoGenerated++;
    }
    
    // 可翻译统计（仅对CaptionTrack有效）
    if ('isTranslatable' in track && track.isTranslatable) {
      stats.translatable++;
    }
  });
  
  return stats;
}

/**
 * 字幕轨道调试信息格式化
 * 
 * @param tracks 字幕轨道数组
 * @param title 标题
 * @returns 格式化的调试字符串
 */
export function formatCaptionTracksDebug(
  tracks: (CaptionTrack | SimplifiedCaptionTrack)[], 
  title: string = '字幕轨道信息'
): string {
  const stats = getCaptionTrackStats(tracks);
  
  let output = `\n=== ${title} ===\n`;
  output += `总计: ${stats.total} 条轨道\n`;
  output += `自动生成: ${stats.autoGenerated} 条\n`;
  output += `可翻译: ${stats.translatable} 条\n`;
  output += `语言分布:\n`;
  
  Object.entries(stats.byLanguage).forEach(([lang, count]) => {
    output += `  - ${lang}: ${count} 条\n`;
  });
  
  output += `详细信息:\n`;
  tracks.forEach((track, index) => {
    const displayName = getTrackDisplayName(track);
    const autoGen = isAutoGeneratedTrack(track) ? ' [自动]' : '';
    output += `  ${index + 1}. ${track.languageCode} - ${displayName}${autoGen}\n`;
  });
  
  return output;
} 